/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {
    val greeting: String
        get() {
            return "Hola mundazo!"
        }
}

fun main() {
    println(App().greeting)
}
